# Generated by Django 3.2.5 on 2021-07-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllsafeWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('total_request', models.BigIntegerField(default=0)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
